language: node_js
node_js:
 - "node"
env:
 - CODECOV_TOKEN="cd04e9e7-26bd-4dc9-be7c-86e59b8c31c9"
before_script: cd frontend
script:
  - npm install
  - npm run lint
  - npm run test-frontend
  - npm run build