language: node_js
node_js:
 - "node"
env:
 - CODECOV_TOKEN="cd04e9e7-26bd-4dc9-be7c-86e59b8c31c9"
 services:
  - docker
before_script:
  - docker pull orientdb
  - docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb
  - cd frontend
script:
  - npm install
  - npm run lint
  - npm run test-frontend
  - npm run build
  - cd ..
  - npm run build
  - npm run codecv